### ISSUE TITLE
Any plans to add AJAX support to the grid?

### ISSUE THREAD

**Issue by jfrank14** [MRCollective/AspNet.Mvc.Grid#2]
I love the grid, but I need to be able to load data via AJAX calls, and also to feed data to the grid from JSON data returned from a web service. Are there any plans to support scenarios like this? Thanks.

**Comment by robdmoore** [comment]
Not really. If I want AJAX functionality I will generally throw in a library like jQuery data tables or similar.  More than happy to receive pull requests though, but given there are so many options out there I'd be hesitant to lock this (rather general) library into something specific.

I believe there are other .NET libraries for grids that include AJAX support ootb (although when I've looked at those libraries they have been pretty complex so I've stayed away preferring to wire in the JavaScript library myself.

**Comment by jfrank14** [comment]
Wait, are you saying that I could hook up jQuery data tables to the table generated by the MVC grid? That would be ideal, actually, but I wasn't sure how the data tables chrome (pager, search bar, etc) would interact with the chrome generated by the grid. Also, the MVC grid wants a model that's a list of objects, whereas I don't have such a list in the scenario where I want to send the grid empty and have it populate via AJAX.

Would you happen to have an example or code sample of how to do this?

**Comment by robdmoore** [comment]
Yep, it's pretty easy. Just give the table an id attribute using the Mvc Grid library (or some other way to identify it) and then target it with jquery as you would if you hand rolled the table html.

If you want an empty grid it's pretty easy:

```c#
@Html.Grid(Enumerable.Empty<MyType>()).Columns(...)...
```

**Comment by jfrank14** [comment]
This is very helpful, thanks! Giving it a try now.

**Comment by jfrank14** [comment]
This didn't actually work. When I specify an empty model list, the grid doesn't write the header row columns, and this seems to break datatables; it just says "Processing..." and never calls my REST endpoint to get the data. I think datatables needs the header to be there even if there's no data. Is there a way to get the grid to write that header?

**Comment by robdmoore** [comment]
Hmm, actually yeah - looking at the code it doesn't render the headers if the data source is empty because instead it displays a message.

If you want to add in an option to allow someone to override it to display headers when it's empty for this sort of scenario I'm happy to get it merged in and to help where I can. Too busy at the moment to write it myself I'm afraid. If you think that would be useful then maybe start by raising a separate issue so it can be tracked.

Alternatively, the workaround for the moment would be to have a single item in your model. Presumably jquery data tables will override it anyway based on it's ajax requests? When we've used it in the past we actually put the full table of data in and just used the pagination and sorting functionality inline since there was only a couple of hundred records (hence why I didn't realise the problem with empty data source).

**Comment by jfrank14** [comment]
It does seem to work to add a dummy record, so I'll do that for now. I'd love to be able to contribute the fix, but I'm not sure I would know where to begin.

**Comment by jfrank14** [comment]
Ugh, I spoke a little too soon. When I add a dummy row, that row is visible for the length of time it takes for the AJAX request to return, and that doesn't look good. I wonder what the cleanest way around this would be.

**Comment by robdmoore** [comment]
You could put a snippet of JavaScript directly after the table that deletes that row?
